### ISSUE TITLE
Links on https://rulegroups.com don't provide proper rule groups format

### ISSUE THREAD

**Issue by kadutskyi** [naveednajam/Little-Snitch---Rule-GroupsV2#2]
Hi @naveednajam I was trying to subscribe to some rule groups from you website but when I do that each subscribed rule group has only one rule with all domains in it. And it doesn't block anything. 

According to the this page https://help.obdev.at//littlesnitch4/ref-lsrules-file-format you are using 
````json
{
  "name": "LaunchBar Software Update",
  "description": "This rule allows LaunchBar to check for updates.",
  "rules": [
    {
      "action": "allow",
      "process": "/Applications/LaunchBar.app/Contents/MacOS/LaunchBar",
      "remote-hosts": "sw-update.obdev.at"
    }
  ]
}
````
But it says that you will need to provide action, process for each domain.

In your Github repo you use a different approach (which works)

````json
{
    "name": "Social Media Block List",
    "description": "Blocks access to popular social media sites.",
    "denied-remote-domains": ["facebook.com", "twitter.com", "youtube.com"]
}
````

**Comment by naveednajam** [comment]
Hi @kadutskyi thanks for trying rulegroups and pointing out the issue. why all the domains are in single rule is to work around two limitation little snitch rule group implementation.  

1. to specify the direction in/out
2. rule group priority

it's strange to know that rules are not working for you. can you point out a specific rule group which did not work? so I will look into it.

**Comment by kadutskyi** [comment]
@naveednajam please take a look at this [screencast](https://www.loom.com/share/7f856e0ee8ac4eb39272577704843c1c)
You will see that I subscribed to "Ads / Tracking / Malware /Porn | easylist" but that didn't work for me and one of the domains is still accessible from my browser. 
Then I duplicate that rule and it still isn't working. And then I add spaces between domains in that duplicated rule and it starts working.

**Comment by naveednajam** [comment]
@kadutskyi I looked at the screen cast thank for pointing out the issue and finding the solution as well. For now I reverted back to rule per domain format same as in V1. Can you check if things are working at your end?

I guess the format broke during the last little snitch update. any way I don't like to keep all domains in one rule as it take away the flexibility to exclude a single domain from the set. unfortunately little snitch does not support priority tag in this format. For now I guess not many people are using priority any way for rule groups.

**Comment by kadutskyi** [comment]
@naveednajam Thanks! It works now. But I see that ads_easylist has some strange rule that blocks all connections to any domain with ".com".

<img width="456" alt="Screen Shot 2020-10-29 at 12 39 59 AM" src="https://user-images.githubusercontent.com/10780527/97539797-d5984800-197f-11eb-8e70-33f8b404671c.png">

**Comment by naveednajam** [comment]
fixed it. check again and you might have to update all the rulegroups.

**Comment by kadutskyi** [comment]
Thank you @naveednajam! Works perfectly
